<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-139153976-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }
        gtag('js', new Date());

        gtag('config', 'UA-139153976-1');
    </script>


    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Glimpse Wearables</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
        integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

    <!-- Fonts -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css"
        integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">

    <!-- IMG popup CSS -->
    <link href="resources/magnific-popup/magnific-popup.css" rel="stylesheet">
    

    <!-- Stylesheet -->
    <link href="css/glimpse.css" rel="stylesheet">

</head>

<body id="page-top">
    <?php include 'navbar.html';?>

    <section style="padding: 0; padding-top: 6em;" id="mobileapp">
        <div class="row">
            <div class="col-lg-8 mx-auto text-center">
                <h2 class="section-heading">Companion App</h2>
                <hr class="my-4">
            </div>
        </div>
        <div class="container-fluid">
            <div class="row flex-column-reverse flex-md-row py-5">
                <div class="col-md text-center order-last">
                    <img src="img/mobile/1.png" alt="" class="img-fluid">
                </div>
                <div class="col-md text-center order-first align-self-center pt-4">
                    <h1>Events</h1>
                <p>
                    We take your favorite moments from the night, and magically curate your own personal aftermovie
                    so you can relive the event long after it's over.
                </p>
                <a class="btn btn-primary btn-xl js-scroll-trigger" href="events.php">Events</a>
                </div>
            </div>
            <div class="row py-5">
                <div class="col-md text-center">
                    <img src="img/mobile/2.png" alt="" class="img-fluid">
                </div>
                <div class="col-md text-center align-self-center pt-4">
                    <h1>Relive the memory</h1>
                <p>
                    We feature the best content from the event, generated by fans and performers.
                </p>
                </div>
            </div>
            <div class="row flex-column-reverse flex-md-row py-5">
                <div class="col-md text-center align-self-center pt-4">
                    <h1>Share it</h1>
                <p>
                    View and share all of your favortite moments directly on the app, or through your favorite
                    social media outlet.
                </p>
                </div>
                <div class="col-md text-center">
                    <img src="img/mobile/3.png" alt="" class="img-fluid">
                </div>
            </div>
        </div>
    </section>

    <!-- Bootstrap core JavaScript -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"
        integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"
        integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous">
    </script>

    <!-- Plugin JavaScript -->
    <script src="resources/jquery-easing/jquery.easing.min.js"></script>
    <script src="resources/scrollreveal/scrollreveal.min.js"></script>
    <script src="resources/magnific-popup/jquery.magnific-popup.min.js"></script>
    

    <!-- Custom scripts for this template -->
    <script src="js/glimpse.js"></script>

</body>

</html>